# Manages the level data for each level

level_0 = {
    'terrain': '../levels/0/level_0_Terrain.csv',
    'coins': '../levels/0/level_0_Coins.csv',
    'fg palms': '../levels/0/level_0_Fg_Palms.csv',
    'bg palms': '../levels/0/level_0_Bg_Palms.csv',
    'crates': '../levels/0/level_0_Crates.csv',
    'enemies': '../levels/0/level_0_Enemies.csv',
    'constraints': '../levels/0/level_0_Constraints.csv',
    'player': '../levels/0/level_0_Player.csv',
    'grass': '../levels/0/level_0_Grass.csv',
    'diamond': '../levels/0/level_0_Diamond.csv',
    'node_pos': (200, 100),
    'unlock': 1,
    'graphics': '../graphics/overworld/0',
    'music': '../audio/level_0.ogg'}
level_1 = {
    'terrain': '../levels/1/level_1_Terrain.csv',
    'coins': '../levels/1/level_1_Coins.csv',
    'fg palms': '../levels/1/level_1_Fg_Palms.csv',
    'bg palms': '../levels/1/level_1_Bg_Palms.csv',
    'crates': '../levels/1/level_1_Crates.csv',
    'enemies': '../levels/1/level_1_Enemies.csv',
    'constraints': '../levels/1/level_1_Constraints.csv',
    'player': '../levels/1/level_1_Player.csv',
    'grass': '../levels/1/level_1_Grass.csv',
    'diamond': '../levels/1/level_1_Diamond.csv',
    'node_pos': (500, 100),
    'unlock': 2,
    'graphics': '../graphics/overworld/1',
    'music': '../audio/level_1.ogg'}
level_2 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (800, 100),
    'unlock': 3,
    'graphics': '../graphics/overworld/2',
    'music': '../audio/level_2.ogg'}
level_3 = {
    'terrain': '../levels/3/level_3_terrain.csv',
    'coins': '../levels/3/level_3_coins.csv',
    'fg palms': '../levels/3/level_3_fg_Palms.csv',
    'bg palms': '../levels/3/level_3_bg_Palms.csv',
    'crates': '../levels/3/level_3_crates.csv',
    'enemies': '../levels/3/level_3_enemies.csv',
    'constraints': '../levels/3/level_3_constraints.csv',
    'player': '../levels/3/level_3_player.csv',
    'grass': '../levels/3/level_3_grass.csv',
    'diamond': '../levels/3/level_3_diamond.csv',
    'node_pos': (1100, 100),
    'unlock': 4,
    'graphics': '../graphics/overworld/3',
    'music': '../audio/level_3.ogg'}
level_4 = {
    'terrain': '../levels/4/level_4_terrain.csv',
    'coins': '../levels/4/level_4_coins.csv',
    'fg palms': '../levels/4/level_4_fg_palms.csv',
    'bg palms': '../levels/4/level_4_bg_palms.csv',
    'crates': '../levels/4/level_4_crates.csv',
    'enemies': '../levels/4/level_4_enemies.csv',
    'constraints': '../levels/4/level_4_constraints.csv',
    'player': '../levels/4/level_4_player.csv',
    'grass': '../levels/4/level_4_grass.csv',
    'diamond': '../levels/4/level_4_diamond.csv',
    'node_pos': (1400, 100),
    'unlock': 5,
    'graphics': '../graphics/overworld/4',
    'music': '../audio/level_4.ogg'}
level_5 = {
    'terrain': '../levels/5/level_5_terrain.csv',
    'coins': '../levels/5/level_5_coins.csv',
    'fg palms': '../levels/5/level_5_fg_Palms.csv',
    'bg palms': '../levels/5/level_5_bg_Palms.csv',
    'crates': '../levels/5/level_5_crates.csv',
    'enemies': '../levels/5/level_5_enemies.csv',
    'constraints': '../levels/5/level_5_constraints.csv',
    'player': '../levels/5/level_5_player.csv',
    'grass': '../levels/5/level_5_grass.csv',
    'diamond': '../levels/5/level_5_diamond.csv',
    'node_pos': (1700, 100),
    'unlock': 6,
    'graphics': '../graphics/overworld/5',
    'music': '../audio/level_5.ogg'}
level_6 = {
    'sand_terrain': '../levels/6/level_6_sand_terrain.csv',
    'coins': '../levels/6/level_6_coins.csv',
    'fg palms': '../levels/6/level_6_fg_palms.csv',
    'bg palms': '../levels/6/level_6_bg_palms.csv',
    'crates': '../levels/6/level_6_crates.csv',
    'enemies': '../levels/6/level_6_enemies.csv',
    'constraints': '../levels/6/level_6_constraints.csv',
    'player': '../levels/6/level_6_player.csv',
    'grass': '../levels/6/level_6_grass.csv',
    'diamond': '../levels/6/level_6_diamond.csv',
    'node_pos': (1700, 400),
    'unlock': 7,
    'graphics': '../graphics/overworld/0',
    'music': '../audio/level_6.ogg'}
level_7 = {
    'sand_terrain': '../levels/7/level_7_terrain.csv',
    'coins': '../levels/7/level_7_coins.csv',
    'fg palms': '../levels/7/level_7_fg_palms.csv',
    'bg palms': '../levels/7/level_7_bg_palms.csv',
    'crates': '../levels/7/level_7_crates.csv',
    'enemies': '../levels/7/level_7_enemies.csv',
    'constraints': '../levels/7/level_7_constraints.csv',
    'player': '../levels/7/level_7_player.csv',
    'grass': '../levels/7/level_7_grass.csv',
    'diamond': '../levels/7/level_7_diamond.csv',
    'node_pos': (1400, 400),
    'unlock': 8,
    'graphics': '../graphics/overworld/1',
    'music': '../audio/level_7.ogg'}
level_8 = {
    'sand_terrain': '../levels/8/level_8_terrain.csv',
    'coins': '../levels/8/level_8_coins.csv',
    'fg palms': '../levels/8/level_8_fg_Palms.csv',
    'bg palms': '../levels/8/level_8_bg_Palms.csv',
    'crates': '../levels/8/level_8_crates.csv',
    'enemies': '../levels/8/level_8_enemies.csv',
    'constraints': '../levels/8/level_8_constraints.csv',
    'player': '../levels/8/level_8_player.csv',
    'grass': '../levels/8/level_8_grass.csv',
    'diamond': '../levels/8/level_8_diamond.csv',
    'node_pos': (1100, 400),
    'unlock': 9,
    'graphics': '../graphics/overworld/2',
    'music': '../audio/level_8.ogg'}
level_9 = {
    'sand_terrain': '../levels/9/level_9_terrain.csv',
    'coins': '../levels/9/level_9_coins.csv',
    'fg palms': '../levels/9/level_9_fg_Palms.csv',
    'bg palms': '../levels/9/level_9_bg_Palms.csv',
    'crates': '../levels/9/level_9_crates.csv',
    'enemies': '../levels/9/level_9_enemies.csv',
    'constraints': '../levels/9/level_9_constraints.csv',
    'player': '../levels/9/level_9_player.csv',
    'grass': '../levels/9/level_9_grass.csv',
    'diamond': '../levels/9/level_9_diamond.csv',
    'node_pos': (800, 400),
    'unlock': 10,
    'graphics': '../graphics/overworld/3',
    'music': '../audio/level_9.ogg'}
level_10 = {
    'sand_terrain': '../levels/10/level_10_terrain.csv',
    'coins': '../levels/10/level_10_coins.csv',
    'fg palms': '../levels/10/level_10_fg_Palms.csv',
    'bg palms': '../levels/10/level_10_bg_Palms.csv',
    'crates': '../levels/10/level_10_crates.csv',
    'enemies': '../levels/10/level_10_enemies.csv',
    'constraints': '../levels/10/level_10_constraints.csv',
    'player': '../levels/10/level_10_player.csv',
    'grass': '../levels/10/level_10_grass.csv',
    'diamond': '../levels/10/level_10_diamond.csv',
    'node_pos': (500, 400),
    'unlock': 11,
    'graphics': '../graphics/overworld/4',
    'music': '../audio/level_10.ogg'}
level_11 = {
    'sand_terrain': '../levels/11/level_11_terrain.csv',
    'coins': '../levels/11/level_11_coins.csv',
    'fg palms': '../levels/11/level_11_fg_Palms.csv',
    'bg palms': '../levels/11/level_11_bg_Palms.csv',
    'crates': '../levels/11/level_11_crates.csv',
    'enemies': '../levels/11/level_11_enemies.csv',
    'constraints': '../levels/11/level_11_constraints.csv',
    'player': '../levels/11/level_11_player.csv',
    'grass': '../levels/11/level_11_grass.csv',
    'diamond': '../levels/11/level_11_diamond.csv',
    'node_pos': (200, 400),
    'unlock': 12,
    'graphics': '../graphics/overworld/5',
    'music': '../audio/level_11.ogg'}
level_12 = {
    'soft_terrain': '../levels/12/level_12_terrain.csv',
    'coins': '../levels/12/level_12_coins.csv',
    'fg palms': '../levels/12/level_12_fg_Palms.csv',
    'bg palms': '../levels/12/level_12_bg_Palms.csv',
    'crates': '../levels/12/level_12_crates.csv',
    'enemies': '../levels/12/level_12_enemies.csv',
    'constraints': '../levels/12/level_12_constraints.csv',
    'player': '../levels/12/level_12_player.csv',
    'grass': '../levels/12/level_12_grass.csv',
    'diamond': '../levels/12/level_12_diamond.csv',
    'node_pos': (200, 700),
    'unlock': 13,
    'graphics': '../graphics/overworld/0',
    'music': '../audio/level_12.ogg'}
level_13 = {
    'soft_terrain': '../levels/13/level_13_terrain.csv',
    'coins': '../levels/13/level_13_coins.csv',
    'fg palms': '../levels/13/level_13_fg_Palms.csv',
    'bg palms': '../levels/13/level_13_bg_Palms.csv',
    'crates': '../levels/13/level_13_crates.csv',
    'enemies': '../levels/13/level_13_enemies.csv',
    'constraints': '../levels/13/level_13_constraints.csv',
    'player': '../levels/13/level_13_player.csv',
    'grass': '../levels/13/level_13_grass.csv',
    'diamond': '../levels/13/level_13_diamond.csv',
    'node_pos': (500, 700),
    'unlock': 14,
    'graphics': '../graphics/overworld/1',
    'music': '../audio/level_13.ogg'}
level_14 = {
    'soft_terrain': '../levels/14/level_14_terrain.csv',
    'coins': '../levels/14/level_14_coins.csv',
    'fg palms': '../levels/14/level_14_fg_Palms.csv',
    'bg palms': '../levels/14/level_14_bg_Palms.csv',
    'crates': '../levels/14/level_14_crates.csv',
    'enemies': '../levels/14/level_14_enemies.csv',
    'constraints': '../levels/14/level_14_constraints.csv',
    'player': '../levels/14/level_14_player.csv',
    'grass': '../levels/14/level_14_grass.csv',
    'diamond': '../levels/14/level_14_diamond.csv',
    'node_pos': (800, 700),
    'unlock': 15,
    'graphics': '../graphics/overworld/2',
    'music': '../audio/level_14.ogg'}
level_15 = {
    'soft_terrain': '../levels/15/level_15_terrain.csv',
    'coins': '../levels/15/level_15_coins.csv',
    'fg palms': '../levels/15/level_15_fg_Palms.csv',
    'bg palms': '../levels/15/level_15_bg_Palms.csv',
    'crates': '../levels/15/level_15_crates.csv',
    'enemies': '../levels/15/level_15_enemies.csv',
    'constraints': '../levels/15/level_15_constraints.csv',
    'player': '../levels/15/level_15_player.csv',
    'grass': '../levels/15/level_15_grass.csv',
    'diamond': '../levels/15/level_15_diamond.csv',
    'node_pos': (1100, 700),
    'unlock': 16,
    'graphics': '../graphics/overworld/3',
    'music': '../audio/level_15.ogg'}
level_16 = {
    'soft_terrain': '../levels/16/level_16_terrain.csv',
    'coins': '../levels/16/level_16_coins.csv',
    'fg palms': '../levels/16/level_16_fg_Palm.csv',
    'bg palms': '../levels/16/level_16_bg_Palm.csv',
    'crates': '../levels/16/level_16_crates.csv',
    'enemies': '../levels/16/level_16_enemies.csv',
    'constraints': '../levels/16/level_16_constraints.csv',
    'player': '../levels/16/level_16_player.csv',
    'grass': '../levels/16/level_16_grass.csv',
    'diamond': '../levels/16/level_16_diamond.csv',
    'node_pos': (1400, 700),
    'unlock': 17,
    'graphics': '../graphics/overworld/4',
    'music': '../audio/level_16.ogg'}
level_17 = {
    'soft_terrain': '../levels/17/level_17_terrain.csv',
    'coins': '../levels/17/level_17_coins.csv',
    'fg palms': '../levels/17/level_17_fg_Palms.csv',
    'bg palms': '../levels/17/level_17_bg_Palms.csv',
    'crates': '../levels/17/level_17_crates.csv',
    'enemies': '../levels/17/level_17_enemies.csv',
    'constraints': '../levels/17/level_17_constraints.csv',
    'player': '../levels/17/level_17_player.csv',
    'grass': '../levels/17/level_17_grass.csv',
    'diamond': '../levels/17/level_17_diamond.csv',
    'node_pos': (1700, 700),
    'unlock': 18,
    'graphics': '../graphics/overworld/5',
    'music': '../audio/level_17.ogg'}
level_18 = {
    'terrain': '../levels/18/level_18_terrain.csv',
    'coins': '../levels/18/level_18_coins.csv',
    'fg palms': '../levels/18/level_18_fg_Palms.csv',
    'bg palms': '../levels/18/level_18_bg_Palms.csv',
    'crates': '../levels/18/level_18_crates.csv',
    'enemies': '../levels/18/level_18_enemies.csv',
    'constraints': '../levels/18/level_18_constraints.csv',
    'player': '../levels/18/level_18_player.csv',
    'grass': '../levels/18/level_18_grass.csv',
    'diamond': '../levels/18/level_18_diamond.csv',
    'node_pos': (1400, 900),
    'unlock': 19,
    'graphics': '../graphics/overworld/0',
    'music': '../audio/level_18.ogg'}
level_19 = {
    'terrain': '../levels/19/level_19_terrain.csv',
    'coins': '../levels/19/level_19_coins.csv',
    'fg palms': '../levels/19/level_19_fg_Palms.csv',
    'bg palms': '../levels/19/level_19_bg_Palms.csv',
    'crates': '../levels/19/level_19_crates.csv',
    'enemies': '../levels/19/level_19_enemies.csv',
    'constraints': '../levels/19/level_19_constraints.csv',
    'player': '../levels/19/level_19_player.csv',
    'grass': '../levels/19/level_19_grass.csv',
    'diamond': '../levels/19/level_19_diamond.csv',
    'node_pos': (800, 900),
    'unlock': 20,
    'graphics': '../graphics/overworld/1',
    'music': '../audio/level_19.ogg'}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5,
    6: level_6,
    7: level_7,
    8: level_8,
    9: level_9,
    10: level_10,
    11: level_11,
    12: level_12,
    13: level_13,
    14: level_14,
    15: level_15,
    16: level_16,
    17: level_17,
    18: level_18,
    19: level_19,
}
