from path import ASSET

# Manages the level data for each level
level_0 = {
    'terrain': ASSET('levels', '0', 'level_0_Terrain.csv'),
    'coins': ASSET('levels', '0', 'level_0_Coins.csv'),
    'fg palms': ASSET('levels', '0', 'level_0_Fg_Palms.csv'),
    'bg palms': ASSET('levels', '0', 'level_0_Bg_Palms.csv'),
    'crates': ASSET('levels', '0', 'level_0_Crates.csv'),
    'enemies': ASSET('levels', '0', 'level_0_Enemies.csv'),
    'constraints': ASSET('levels', '0', 'level_0_Constraints.csv'),
    'player': ASSET('levels', '0', 'level_0_Player.csv'),
    'grass': ASSET('levels', '0', 'level_0_Grass.csv'),
    'diamond': ASSET('levels', '0', 'level_0_Diamond.csv'),
    'node_pos': (200, 100),
    'unlock': 1,
    'graphics': ASSET('graphics', 'overworld', '0'),
    'music': ASSET('audio', 'level_0.ogg')}
level_1 = {
    'terrain': ASSET('levels', '1', 'level_1_Terrain.csv'),
    'coins': ASSET('levels', '1', 'level_1_Coins.csv'),
    'fg palms': ASSET('levels', '1', 'level_1_Fg_Palms.csv'),
    'bg palms': ASSET('levels', '1', 'level_1_Bg_Palms.csv'),
    'crates': ASSET('levels', '1', 'level_1_Crates.csv'),
    'enemies': ASSET('levels', '1', 'level_1_Enemies.csv'),
    'constraints': ASSET('levels', '1', 'level_1_Constraints.csv'),
    'player': ASSET('levels', '1', 'level_1_Player.csv'),
    'grass': ASSET('levels', '1', 'level_1_Grass.csv'),
    'diamond': ASSET('levels', '1', 'level_1_Diamond.csv'),
    'node_pos': (500, 100),
    'unlock': 2,
    'graphics': ASSET('graphics', 'overworld', '1'),
    'music': ASSET('audio', 'level_1.ogg')}
level_2 = {
    'terrain': ASSET('levels', '2', 'level_2_terrain.csv'),
    'coins': ASSET('levels', '2', 'level_2_coins.csv'),
    'fg palms': ASSET('levels', '2', 'level_2_fg_Palms.csv'),
    'bg palms': ASSET('levels', '2', 'level_2_bg_Palms.csv'),
    'crates': ASSET('levels', '2', 'level_2_crates.csv'),
    'enemies': ASSET('levels', '2', 'level_2_enemies.csv'),
    'constraints': ASSET('levels', '2', 'level_2_constraints.csv'),
    'player': ASSET('levels', '2', 'level_2_player.csv'),
    'grass': ASSET('levels', '2', 'level_2_grass.csv'),
    'diamond': ASSET('levels', '2', 'level_2_diamond.csv'),
    'node_pos': (800, 100),
    'unlock': 3,
    'graphics': ASSET('graphics', 'overworld', '2'),
    'music': ASSET('audio', 'level_2.ogg')}
level_3 = {
    'terrain': ASSET('levels', '3', 'level_3_terrain.csv'),
    'coins': ASSET('levels', '3', 'level_3_coins.csv'),
    'fg palms': ASSET('levels', '3', 'level_3_fg_Palms.csv'),
    'bg palms': ASSET('levels', '3', 'level_3_bg_Palms.csv'),
    'crates': ASSET('levels', '3', 'level_3_crates.csv'),
    'enemies': ASSET('levels', '3', 'level_3_enemies.csv'),
    'constraints': ASSET('levels', '3', 'level_3_constraints.csv'),
    'player': ASSET('levels', '3', 'level_3_player.csv'),
    'grass': ASSET('levels', '3', 'level_3_grass.csv'),
    'diamond': ASSET('levels', '3', 'level_3_diamond.csv'),
    'node_pos': (1100, 100),
    'unlock': 4,
    'graphics': ASSET('graphics', 'overworld', '3'),
    'music': ASSET('audio', 'level_3.ogg')}
level_4 = {
    'terrain': ASSET('levels', '4', 'level_4_terrain.csv'),
    'coins': ASSET('levels', '4', 'level_4_coins.csv'),
    'fg palms': ASSET('levels', '4', 'level_4_fg_palms.csv'),
    'bg palms': ASSET('levels', '4', 'level_4_bg_palms.csv'),
    'crates': ASSET('levels', '4', 'level_4_crates.csv'),
    'enemies': ASSET('levels', '4', 'level_4_enemies.csv'),
    'constraints': ASSET('levels', '4', 'level_4_constraints.csv'),
    'player': ASSET('levels', '4', 'level_4_player.csv'),
    'grass': ASSET('levels', '4', 'level_4_grass.csv'),
    'diamond': ASSET('levels', '4', 'level_4_diamond.csv'),
    'node_pos': (1400, 100),
    'unlock': 5,
    'graphics': ASSET('graphics', 'overworld', '4'),
    'music': ASSET('audio', 'level_4.ogg')}
level_5 = {
    'terrain': ASSET('levels', '5', 'level_5_terrain.csv'),
    'coins': ASSET('levels', '5', 'level_5_coins.csv'),
    'fg palms': ASSET('levels', '5', 'level_5_fg_Palms.csv'),
    'bg palms': ASSET('levels', '5', 'level_5_bg_Palms.csv'),
    'crates': ASSET('levels', '5', 'level_5_crates.csv'),
    'enemies': ASSET('levels', '5', 'level_5_enemies.csv'),
    'constraints': ASSET('levels', '5', 'level_5_constraints.csv'),
    'player': ASSET('levels', '5', 'level_5_player.csv'),
    'grass': ASSET('levels', '5', 'level_5_grass.csv'),
    'diamond': ASSET('levels', '5', 'level_5_diamond.csv'),
    'node_pos': (1700, 100),
    'unlock': 6,
    'graphics': ASSET('graphics', 'overworld', '5'),
    'music': ASSET('audio', 'level_5.ogg')}
level_6 = {
    'sand_terrain': ASSET('levels', '6', 'level_6_sand_terrain.csv'),
    'coins': ASSET('levels', '6', 'level_6_coins.csv'),
    'fg palms': ASSET('levels', '6', 'level_6_fg_palms.csv'),
    'bg palms': ASSET('levels', '6', 'level_6_bg_palms.csv'),
    'crates': ASSET('levels', '6', 'level_6_crates.csv'),
    'enemies': ASSET('levels', '6', 'level_6_enemies.csv'),
    'constraints': ASSET('levels', '6', 'level_6_constraints.csv'),
    'player': ASSET('levels', '6', 'level_6_player.csv'),
    'grass': ASSET('levels', '6', 'level_6_grass.csv'),
    'diamond': ASSET('levels', '6', 'level_6_diamond.csv'),
    'node_pos': (1700, 400),
    'unlock': 7,
    'graphics': ASSET('graphics', 'overworld', '0'),
    'music': ASSET('audio', 'level_6.ogg')}
level_7 = {
    'sand_terrain': ASSET('levels', '7', 'level_7_terrain.csv'),
    'coins': ASSET('levels', '7', 'level_7_coins.csv'),
    'fg palms': ASSET('levels', '7', 'level_7_fg_palms.csv'),
    'bg palms': ASSET('levels', '7', 'level_7_bg_palms.csv'),
    'crates': ASSET('levels', '7', 'level_7_crates.csv'),
    'enemies': ASSET('levels', '7', 'level_7_enemies.csv'),
    'constraints': ASSET('levels', '7', 'level_7_constraints.csv'),
    'player': ASSET('levels', '7', 'level_7_player.csv'),
    'grass': ASSET('levels', '7', 'level_7_grass.csv'),
    'diamond': ASSET('levels', '7', 'level_7_diamond.csv'),
    'node_pos': (1400, 400),
    'unlock': 8,
    'graphics': ASSET('graphics', 'overworld', '1'),
    'music': ASSET('audio', 'level_7.ogg')}
level_8 = {
    'sand_terrain': ASSET('levels', '8', 'level_8_terrain.csv'),
    'coins': ASSET('levels', '8', 'level_8_coins.csv'),
    'fg palms': ASSET('levels', '8', 'level_8_fg_Palms.csv'),
    'bg palms': ASSET('levels', '8', 'level_8_bg_Palms.csv'),
    'crates': ASSET('levels', '8', 'level_8_crates.csv'),
    'enemies': ASSET('levels', '8', 'level_8_enemies.csv'),
    'constraints': ASSET('levels', '8', 'level_8_constraints.csv'),
    'player': ASSET('levels', '8', 'level_8_player.csv'),
    'grass': ASSET('levels', '8', 'level_8_grass.csv'),
    'diamond': ASSET('levels', '8', 'level_8_diamond.csv'),
    'node_pos': (1100, 400),
    'unlock': 9,
    'graphics': ASSET('graphics', 'overworld', '2'),
    'music': ASSET('audio', 'level_8.ogg')}
level_9 = {
    'sand_terrain': ASSET('levels', '9', 'level_9_terrain.csv'),
    'coins': ASSET('levels', '9', 'level_9_coins.csv'),
    'fg palms': ASSET('levels', '9', 'level_9_fg_Palms.csv'),
    'bg palms': ASSET('levels', '9', 'level_9_bg_Palms.csv'),
    'crates': ASSET('levels', '9', 'level_9_crates.csv'),
    'enemies': ASSET('levels', '9', 'level_9_enemies.csv'),
    'constraints': ASSET('levels', '9', 'level_9_constraints.csv'),
    'player': ASSET('levels', '9', 'level_9_player.csv'),
    'grass': ASSET('levels', '9', 'level_9_grass.csv'),
    'diamond': ASSET('levels', '9', 'level_9_diamond.csv'),
    'node_pos': (800, 400),
    'unlock': 10,
    'graphics': ASSET('graphics', 'overworld', '3'),
    'music': ASSET('audio', 'level_9.ogg')}
level_10 = {
    'sand_terrain': ASSET('levels', '10', 'level_10_terrain.csv'),
    'coins': ASSET('levels', '10', 'level_10_coins.csv'),
    'fg palms': ASSET('levels', '10', 'level_10_fg_Palms.csv'),
    'bg palms': ASSET('levels', '10', 'level_10_bg_Palms.csv'),
    'crates': ASSET('levels', '10', 'level_10_crates.csv'),
    'enemies': ASSET('levels', '10', 'level_10_enemies.csv'),
    'constraints': ASSET('levels', '10', 'level_10_constraints.csv'),
    'player': ASSET('levels', '10', 'level_10_player.csv'),
    'grass': ASSET('levels', '10', 'level_10_grass.csv'),
    'diamond': ASSET('levels', '10', 'level_10_diamond.csv'),
    'node_pos': (500, 400),
    'unlock': 11,
    'graphics': ASSET('graphics', 'overworld', '4'),
    'music': ASSET('audio', 'level_10.ogg')}
level_11 = {
    'sand_terrain': ASSET('levels', '11', 'level_11_terrain.csv'),
    'coins': ASSET('levels', '11', 'level_11_coins.csv'),
    'fg palms': ASSET('levels', '11', 'level_11_fg_Palms.csv'),
    'bg palms': ASSET('levels', '11', 'level_11_bg_Palms.csv'),
    'crates': ASSET('levels', '11', 'level_11_crates.csv'),
    'enemies': ASSET('levels', '11', 'level_11_enemies.csv'),
    'constraints': ASSET('levels', '11', 'level_11_constraints.csv'),
    'player': ASSET('levels', '11', 'level_11_player.csv'),
    'grass': ASSET('levels', '11', 'level_11_grass.csv'),
    'diamond': ASSET('levels', '11', 'level_11_diamond.csv'),
    'node_pos': (200, 400),
    'unlock': 12,
    'graphics': ASSET('graphics', 'overworld', '5'),
    'music': ASSET('audio', 'level_11.ogg')}
level_12 = {
    'soft_terrain': ASSET('levels', '12', 'level_12_terrain.csv'),
    'coins': ASSET('levels', '12', 'level_12_coins.csv'),
    'fg palms': ASSET('levels', '12', 'level_12_fg_Palms.csv'),
    'bg palms': ASSET('levels', '12', 'level_12_bg_Palms.csv'),
    'crates': ASSET('levels', '12', 'level_12_crates.csv'),
    'enemies': ASSET('levels', '12', 'level_12_enemies.csv'),
    'constraints': ASSET('levels', '12', 'level_12_constraints.csv'),
    'player': ASSET('levels', '12', 'level_12_player.csv'),
    'grass': ASSET('levels', '12', 'level_12_grass.csv'),
    'diamond': ASSET('levels', '12', 'level_12_diamond.csv'),
    'node_pos': (200, 700),
    'unlock': 13,
    'graphics': ASSET('graphics', 'overworld', '0'),
    'music': ASSET('audio', 'level_12.ogg')}
level_13 = {
    'soft_terrain': ASSET('levels', '13', 'level_13_terrain.csv'),
    'coins': ASSET('levels', '13', 'level_13_coins.csv'),
    'fg palms': ASSET('levels', '13', 'level_13_fg_Palms.csv'),
    'bg palms': ASSET('levels', '13', 'level_13_bg_Palms.csv'),
    'crates': ASSET('levels', '13', 'level_13_crates.csv'),
    'enemies': ASSET('levels', '13', 'level_13_enemies.csv'),
    'constraints': ASSET('levels', '13', 'level_13_constraints.csv'),
    'player': ASSET('levels', '13', 'level_13_player.csv'),
    'grass': ASSET('levels', '13', 'level_13_grass.csv'),
    'diamond': ASSET('levels', '13', 'level_13_diamond.csv'),
    'node_pos': (500, 700),
    'unlock': 14,
    'graphics': ASSET('graphics', 'overworld', '1'),
    'music': ASSET('audio', 'level_13.ogg')}
level_14 = {
    'soft_terrain': ASSET('levels', '14', 'level_14_terrain.csv'),
    'coins': ASSET('levels', '14', 'level_14_coins.csv'),
    'fg palms': ASSET('levels', '14', 'level_14_fg_Palms.csv'),
    'bg palms': ASSET('levels', '14', 'level_14_bg_Palms.csv'),
    'crates': ASSET('levels', '14', 'level_14_crates.csv'),
    'enemies': ASSET('levels', '14', 'level_14_enemies.csv'),
    'constraints': ASSET('levels', '14', 'level_14_constraints.csv'),
    'player': ASSET('levels', '14', 'level_14_player.csv'),
    'grass': ASSET('levels', '14', 'level_14_grass.csv'),
    'diamond': ASSET('levels', '14', 'level_14_diamond.csv'),
    'node_pos': (800, 700),
    'unlock': 15,
    'graphics': ASSET('graphics', 'overworld', '2'),
    'music': ASSET('audio', 'level_14.ogg')}
level_15 = {
    'soft_terrain': ASSET('levels', '15', 'level_15_terrain.csv'),
    'coins': ASSET('levels', '15', 'level_15_coins.csv'),
    'fg palms': ASSET('levels', '15', 'level_15_fg_Palms.csv'),
    'bg palms': ASSET('levels', '15', 'level_15_bg_Palms.csv'),
    'crates': ASSET('levels', '15', 'level_15_crates.csv'),
    'enemies': ASSET('levels', '15', 'level_15_enemies.csv'),
    'constraints': ASSET('levels', '15', 'level_15_constraints.csv'),
    'player': ASSET('levels', '15', 'level_15_player.csv'),
    'grass': ASSET('levels', '15', 'level_15_grass.csv'),
    'diamond': ASSET('levels', '15', 'level_15_diamond.csv'),
    'node_pos': (1100, 700),
    'unlock': 16,
    'graphics': ASSET('graphics', 'overworld', '3'),
    'music': ASSET('audio', 'level_15.ogg')}
level_16 = {
    'soft_terrain': ASSET('levels', '16', 'level_16_terrain.csv'),
    'coins': ASSET('levels', '16', 'level_16_coins.csv'),
    'fg palms': ASSET('levels', '16', 'level_16_fg_Palm.csv'),
    'bg palms': ASSET('levels', '16', 'level_16_bg_Palm.csv'),
    'crates': ASSET('levels', '16', 'level_16_crates.csv'),
    'enemies': ASSET('levels', '16', 'level_16_enemies.csv'),
    'constraints': ASSET('levels', '16', 'level_16_constraints.csv'),
    'player': ASSET('levels', '16', 'level_16_player.csv'),
    'grass': ASSET('levels', '16', 'level_16_grass.csv'),
    'diamond': ASSET('levels', '16', 'level_16_diamond.csv'),
    'node_pos': (1400, 700),
    'unlock': 17,
    'graphics': ASSET('graphics', 'overworld', '4'),
    'music': ASSET('audio', 'level_16.ogg')}
level_17 = {
    'soft_terrain': ASSET('levels', '17', 'level_17_terrain.csv'),
    'coins': ASSET('levels', '17', 'level_17_coins.csv'),
    'fg palms': ASSET('levels', '17', 'level_17_fg_Palms.csv'),
    'bg palms': ASSET('levels', '17', 'level_17_bg_Palms.csv'),
    'crates': ASSET('levels', '17', 'level_17_crates.csv'),
    'enemies': ASSET('levels', '17', 'level_17_enemies.csv'),
    'constraints': ASSET('levels', '17', 'level_17_constraints.csv'),
    'player': ASSET('levels', '17', 'level_17_player.csv'),
    'grass': ASSET('levels', '17', 'level_17_grass.csv'),
    'diamond': ASSET('levels', '17', 'level_17_diamond.csv'),
    'node_pos': (1700, 700),
    'unlock': 18,
    'graphics': ASSET('graphics', 'overworld', '5'),
    'music': ASSET('audio', 'level_17.ogg')}
level_18 = {
    'terrain': ASSET('levels', '18', 'level_18_terrain.csv'),
    'coins': ASSET('levels', '18', 'level_18_coins.csv'),
    'fg palms': ASSET('levels', '18', 'level_18_fg_Palms.csv'),
    'bg palms': ASSET('levels', '18', 'level_18_bg_Palms.csv'),
    'crates': ASSET('levels', '18', 'level_18_crates.csv'),
    'enemies': ASSET('levels', '18', 'level_18_enemies.csv'),
    'constraints': ASSET('levels', '18', 'level_18_constraints.csv'),
    'player': ASSET('levels', '18', 'level_18_player.csv'),
    'grass': ASSET('levels', '18', 'level_18_grass.csv'),
    'diamond': ASSET('levels', '18', 'level_18_diamond.csv'),
    'node_pos': (1400, 900),
    'unlock': 19,
    'graphics': ASSET('graphics', 'overworld', '0'),
    'music': ASSET('audio', 'level_18.ogg')}
level_19 = {
    'terrain': ASSET('levels', '19', 'level_19_terrain.csv'),
    'coins': ASSET('levels', '19', 'level_19_coins.csv'),
    'fg palms': ASSET('levels', '19', 'level_19_fg_Palms.csv'),
    'bg palms': ASSET('levels', '19', 'level_19_bg_Palms.csv'),
    'crates': ASSET('levels', '19', 'level_19_crates.csv'),
    'enemies': ASSET('levels', '19', 'level_19_enemies.csv'),
    'constraints': ASSET('levels', '19', 'level_19_constraints.csv'),
    'player': ASSET('levels', '19', 'level_19_player.csv'),
    'grass': ASSET('levels', '19', 'level_19_grass.csv'),
    'diamond': ASSET('levels', '19', 'level_19_diamond.csv'),
    'node_pos': (800, 900),
    'unlock': 20,
    'graphics': ASSET('graphics', 'overworld', '1'),
    'music': ASSET('audio', 'level_19.ogg')}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5,
    6: level_6,
    7: level_7,
    8: level_8,
    9: level_9,
    10: level_10,
    11: level_11,
    12: level_12,
    13: level_13,
    14: level_14,
    15: level_15,
    16: level_16,
    17: level_17,
    18: level_18,
    19: level_19,
}
